spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      authentication-database: none
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.istyazhkina.library.changelogs

hystrix:
  command:
    genres:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    authors:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    books:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000